project:
  type: website

website:
  title: "G2 - Group01"
  navbar:
    left:
      - href: proposal.html
        text: Proposal
      - href: poster.html
        text: Poster
      - href: report.html
        text: Report
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

